### ISSUE TITLE
It seems the DNS server of my probe doesn't work well with my wifi interface

### ISSUE THREAD

**Issue by nguyenvuduc** [clariusdev/solum#19]
This is just an open question to check if you have ever gotten this error with the probe.
When I connect my Windows' 10's wifi to the DIRECT-xxxx wifi network, my network interface is configured with the wrong IP address:

```
Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Wi-Fi 6 AX201 160MHz
   Physical Address. . . . . . . . . : <masked>
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::599f:63d4:f49b:b8ab%9(Preferred)
   Autoconfiguration IPv4 Address. . : 169.254.184.171(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 134234680
   DHCPv6 Client DUID. . . . . . . . : <masked>
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```
the IPv4 address is supposed to be 192.168.1.x/24

My probe software: v9.3.3
Solum: 10.0
I have checked my wifi interface, the IPv4, IPv6 are on. IP are configured to be obtained from DNS server.
If I use my iPhone to connect to the same DIRECT wifi network, the probe configures my phone with a correct IP address.

Thank you and best regards,

**Comment by Alyosha-Karamazov** [comment]
I believe that Windows assigns a 169.254.x.x address when it cannot contact the DHCP server for the network, but it may be that your Windows machine is requesting a particular IP address which is not available. Please check that the IP settings are set to  "Automatic (DHCP)":
https://support.microsoft.com/en-us/windows/change-tcp-ip-settings-bd0a07af-15f5-cd6a-363f-ca2b6f391ace
You can also try running `ipconfig /release` and `ipconfig /renew` from the command prompt to force it to assign a new IP address.
