### ISSUE TITLE
Request: ARM Library for Ubuntu 20/22

### ISSUE THREAD

**Issue by reneahlsdorf** [clariusdev/solum#22]
Hi everyone,

Just wanted to ask if you plan to release libsolum.so builds for ARM64-based Ubuntu (20/22) systems in the future? We've developed our own embedded (NVIDIA Jetson platform - thus ARM) derivative of Ubuntu and would like to integrate the probe into the system. 

Many thanks in advance!

**Comment by clariusk** [comment]
hi there, this is in our queue of future improvements, unfortunately, no timeline on this yet.

**Comment by miltonsegura-cobionix** [comment]
This issue can be closed now. Support for Ubuntu (20/22/23) ARM-64 was added in v11.2.0
