### ISSUE TITLE
Can not make connection to the probe any more due to Network unreachable

### ISSUE THREAD

**Issue by nguyenvuduc** [clariusdev/solum#27]
**Describe the bug**
I can't make a connection to the Clarius Probe anymore with Solum although it works a few days ago. It got network unreachable.
I checked the wifi connection and realized that the Probe's access point didn't assign IP address for my WIFI interface.

I changed my WIFI network to use a static address: 192.168.1.5 but it didn't work either. I got connection failure.

All the attempts were done on Solum's examples:
![image](https://user-images.githubusercontent.com/5864656/224502849-4aa67bbf-1527-49ed-b4d4-8dbbca84ed27.png)
![image](https://user-images.githubusercontent.com/5864656/224502853-cd079bf7-d3ac-4d2f-b7c5-b1c588dd0db7.png)

The Clarius mobile app is working properly and it configured the port to be 5828 instead of a random port.

**To Reproduce**
1. Run Solum_qt example
2. On Cloud tab, enter api token, click Retrieve, check whether the certificates are received successfully
3. Go to BLE tab, click Search, select the probe, click Connect, the other buttons will be enabled.
4. Click AP, notice the IP Address & port of the probe displayed on the task bar
5. Connect your computer's wifi to the probe
6. Click TCP, tab click connect
7. Got connection failed

**Environment:**
- Solum 10.2.2   (solum.dll & solum.lib)
- Development platform: Windows, Qt 6.3.1 MSVC 2019 64bits
- SDK version: 10.2.2
- Clarius App version: 10.2.2-6256+cc63b8dcca

**Comment by julien-l** [comment]
Can you verify the certificate is still valid? Do you have more diagnostic messages from the lib?
