### ISSUE TITLE
Connection fails when using the probe own Wi-Fi "Invalid message response for command set stream IP"

### ISSUE THREAD

**Issue by matteo-ronchetti** [clariusdev/solum#34]
**Describe the bug**
Connection fails and `CusConnectFn` is called with the following arguments
```
ProbeDisconnected, 0, "disconnected"
ConnectionError, 0, "Failed to connect to probe at 192.168.1.1:40355 (networkID 0): Exception ocurred (Invalid message response for command set stream IP (4); contains 0 sub-packets rather than 2))"
ConnectionFailed, 0, "connection failed"
ProbeDisconnected, 0, "disconnected"
ConnectionError, 0, "Failed to connect to probe at 192.168.1.1:40355 (networkID 0): Exception ocurred (Invalid message response for command set stream IP (6); contains 0 sub-packets rather than 2))"
ConnectionFailed, 0, "connection failed"
ProbeDisconnected, 0, "disconnected"
....
```

**To Reproduce**
1. Start the Bluetooth connection
2. Connect to the probe Wi-Fi (I can ping the probe IP)
3. Try connecting with the Solum API

**Environment:**
 - Development platform: Linux
 - SDK version: 10.3.0

**Comment by clariusk** [comment]
can you ensure the probe firmware is updated with the Clarius App to 10.3, there is a known issue of firmware updates not working in Solum which is fixed in the next release.
