### ISSUE TITLE
IMU Licence

### ISSUE THREAD

**Issue by LovisP** [clariusdev/solum#38]
Dear developer-team,
It might not be the right place to ask - but neither your colleauges from sales nor support couldn't answer this question.

Is IMU data accessibility included in the solum licence or does it require buying an additional licence?

Thank you:)

**Comment by julien-l** [comment]
IMU data is included in the Solum license, it is delivered by the imaging callback in the `CusPosInfo` struct:

    typedef void (*CusNewProcessedImageFn)(const void* img, const CusProcessedImageInfo* nfo, int npos, const CusPosInfo* pos);
