### ISSUE TITLE
Porting an Android app that uses mobileapi to Solum API

### ISSUE THREAD

**Issue by delosa** [clariusdev/solum#45]
Has anyone ported a app that uses the mobileapi to use the Solum API?  If yes, what issues did you run into?

**Comment by clariusk** [comment]
Solum is for stand-alone software that does not rely on the Clarius App, so it's for Clarius customers deploying OEM solutions. The big changes are managing the wireless connections manually, including Bluetooth and the Wi-Fi network

**Comment by delosa** [comment]
Our current app uses the Mobile API.   Is Solum a good replacement for the Mobile API or should we just stick with the Mobile API even though Clarius is no longer supporting it?

 

Thank you,

    Nancy

 

From: Kris Dickie ***@***.***> 
Sent: Tuesday, November 14, 2023 5:16 PM
To: clariusdev/solum ***@***.***>
Cc: DeLosa, Nancy - 0224 - MITLL ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [clariusdev/solum] Porting an Android app that uses mobileapi to Solum API (Issue #45)

 

Solum is for stand-alone software that does not rely on the Clarius App, so it's for Clarius customers deploying OEM solutions. The big changes are managing the wireless connections manually, including Bluetooth and the Wi-Fi network —Reply 

ZjQcmQRYFpfptBannerStart




This Message Is From an External Sender 


This message came from outside the Laboratory. 

ZjQcmQRYFpfptBannerEnd

Solum is for stand-alone software that does not rely on the Clarius App, so it's for Clarius customers deploying OEM solutions. The big changes are managing the wireless connections manually, including Bluetooth and the Wi-Fi network

**Comment by delosa** [comment]
Cast API seemed to need a laptop in the loop.  Did I misunderstand that?

 

From: Kris Dickie ***@***.***> 
Sent: Wednesday, November 15, 2023 11:26 AM
To: clariusdev/solum ***@***.***>
Cc: DeLosa, Nancy - 0224 - MITLL ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [clariusdev/solum] Porting an Android app that uses mobileapi to Solum API (Issue #45)

 

Cast API is the replacement for Mobile API, Solum is only available for OEM partners. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <clariusdev/solum/issues/45/1812857524@ github. com> 

ZjQcmQRYFpfptBannerStart




This Message Is From an External Sender 


This message came from outside the Laboratory. 

ZjQcmQRYFpfptBannerEnd

Cast API is the replacement for Mobile API, Solum is only available for OEM partners.

**Comment by clariusk** [comment]
there are desktop versions of Cast, however android and iOS are also supported

**Comment by delosa** [comment]
OK.  Thank you for pointing me in the correct direction.

 

From: Kris Dickie ***@***.***> 
Sent: Wednesday, November 15, 2023 11:34 AM
To: clariusdev/solum ***@***.***>
Cc: DeLosa, Nancy - 0224 - MITLL ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [clariusdev/solum] Porting an Android app that uses mobileapi to Solum API (Issue #45)

 

there are desktop versions of Cast, however android and iOS are also supported — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <clariusdev/solum/issues/45/1812872061@ github. com> 

ZjQcmQRYFpfptBannerStart




This Message Is From an External Sender 


This message came from outside the Laboratory. 

ZjQcmQRYFpfptBannerEnd

there are desktop versions of Cast, however android and iOS are also supported
