### ISSUE TITLE
Detailed information about doppler (color) mode

### ISSUE THREAD

**Issue by danilogr** [clariusdev/solum#47]
Does the API provide any details about the Doppler mode? If not, is the range fixed and documented somewhere?

 For example, the first and last color of the range and their respective value in cm/s ?
![image](https://github.com/clariusdev/solum/assets/1302815/c550a914-09f3-4b23-a147-f196f845724f)

**Comment by clariusk** [comment]
you can use solumGetRange() and pass in DopplerVelocity

**Comment by danilogr** [comment]
What about the color map? From the Clarius mobile app, this seems to be a gradient of 5 colors.
![image](https://github.com/clariusdev/solum/assets/1302815/2a816565-8249-43e5-b28a-c9141a0da6d1)

Can I obtain the gradient colors from the API?

**Comment by clariusk** [comment]
here are the maps we use, there are no SDK functions for obtaining

![map](https://github.com/clariusdev/solum/assets/8701648/3f121d3e-e4bb-4b77-8434-5271cd3a1d28)
![power](https://github.com/clariusdev/solum/assets/8701648/f2f32f61-c74d-45de-bea4-0136e21e9896)

**Comment by danilogr** [comment]
Thank yoU!
