### ISSUE TITLE
Shutting down the ultrasound probe through the power button doesn't always invoke the Power down callback

### ISSUE THREAD

**Issue by danilogr** [clariusdev/solum#49]
**Describe the bug**
After following the correct order of operations to receive ultrasound frames, pressing and holding the power button doesn't always invoke the **power down** callback (`CusPowerDownFn`) defined in `solumInit`.

**To Reproduce**
1. After invoking `solumInit`, connect to the probe (`solumConnect`), set a certificate, and load an application.
2. Unfreeze the probe and scan for a few seconds
3. Wait until the probe freezes, manually freeze the stream, or wait for the frame rate to drop
4. Hold the power button on the probe until the probe shuts down
5. Power Down callback may or may not be called

**Notes**
- I can't tell if the behavior is related to the frame rate, but it doesn't happen when the probe is scanning at a high frame rate.
- During my testing, sometimes `solum` will automatically reconnect to the probe when the probe comes back online on the same network. This happens only if the power-down callback hasn't been invoked (see #44 )

**Environment:**
- SDK variant: Windows
- Development platform: Visual Studio
- SDK version: v11.0.0
- Firmware: v11.0.0-525+bf1bbd364b

**Comment by clariusk** [comment]
it may be due to a race condition between the shutdown of the device and the TCP socket
