### ISSUE TITLE
Request Firmware Version Android

### ISSUE THREAD

**Issue by SeeDeePee** [clariusdev/solum#56]
**Bug Description**
I am receiving inconsistent results when a successful connection has been made to the probe, specifically this code block:

`        @Override
        public void connectionResult(Connection result, int port, String status) {
            Log.d(TAG, "Connection result: " + result + ", port: " + port + ", status: " + status);
            if (result == Connection.ProbeConnected) {
                showMessage("Connected");
            } else if (result == Connection.SwUpdateRequired) {
                showMessage("Firmware update needed");
            } else {
                showMessage("Disconnected");
            }
        }`

Inside my app the user is correctly prompted to do a firmware upgrade when the probe has been used with the Clarius app and wants to use the probe inside my app. The inconsistency occurs during subsequent connections to the probe, about once every 10 connections, the app again prompts the user to update the firmware even though the current version is compatible with the Solum package.

Is there a way to prompt the probe to return its current firmware version so I can use it as a boolean flag. The Clarius app does display the current installed firmware version of the probe and the required firmware version.

**Environment:**
- Android Custom App

Thanks

**Comment by clariusk** [comment]
yes, you can query the GATT device information service over BLE  and read the software revision string

**Comment by SeeDeePee** [comment]
Thank You!
