### ISSUE TITLE
ProcessedImage has a white border - How are MicronsPerPixel defined?

### ISSUE THREAD

**Issue by TheChrizZly** [clariusdev/solum#64]
Hello,
I do get the processed image with the CusNewProcessedImageFn callback.
from the imageinfo I get the information that the image size is 640x480. However. Analysing the data, the first and last 22 columns do have the RGBA values: 0,0,0,0, which results in a real image size of 596x480.

a) Can this observation be correct or is there an error in my implementation? 

b) How are the micronsPerPixel calculated? On a 640x480 image or on the "real" 596x480 image?

Kind regards,
Christian

**Comment by clariusk** [comment]
makes sense, only the raw data would have ultrasound information for each sample, processed data is scan converted (geometrically interpolated), so you always have dead space when specifying an output resolution (think of a curved probe - majority of top part of image is black)
